# Generated by Django 4.0.2 on 2022-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='meetingDays',
            field=models.CharField(choices=[('Sun.', 'Sunday'), ('Mon.', 'Monday'), ('Tue.', 'Tuesday'), ('Wed.', 'Wednesday'), ('Thu.', 'Thursday'), ('Fri.', 'Friday'), ('Sat.', 'Saturday')], default='sunday', max_length=10),
        ),
    ]
