# Generated by Django 4.0.2 on 2022-04-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
