# Generated by Django 4.0.2 on 2022-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
