# Generated by Django 4.0.2 on 2022-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0002_alter_discipline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='meetingDays',
            field=models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='begin_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
