# Generated by Django 4.0.2 on 2022-04-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0002_alter_course_course_title_alter_timeslot_meetingdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_API.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_API.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='requested_user_name',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.ManyToManyField(to='Django_API.AssignedSection')),
            ],
        ),
    ]
