# Generated by Django 4.0.2 on 2022-04-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0003_assignedsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='assignments',
        ),
        migrations.AddField(
            model_name='assignedsection',
            name='solution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Django_API.solution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='assignment_count',
            field=models.IntegerField(default=0),
        ),
    ]
