# Generated by Django 4.0.2 on 2022-04-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0003_timeslot_meetingdays_alter_timeslot_begin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='meetingTimeString',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='meetingDays',
            field=models.CharField(choices=[('Sun.', 'Sunday'), ('Mon.', 'Monday'), ('Tu.', 'Tuesday'), ('Wed.', 'Wednesday'), ('Th.', 'Thursday'), ('Fri.', 'Friday'), ('Sat.', 'Saturday')], default='sunday', max_length=10),
        ),
    ]
