# Generated by Django 4.0.2 on 2022-04-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_API', '0004_section_meetingtimestring_alter_timeslot_meetingdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='meetingTimeString',
        ),
    ]
